name: Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: silverorange/actions-setup-php@v2
        with:
          php-version: '8.2'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: 'composer install'

      - name: Run tests
        timeout-minutes: 5
        run: |
          composer run phpcs:ci
          composer run phpstan:ci
          composer run test
